Lesson 2
Seaman51/geekshop pull request #2
Opened 2021-01-24 19:12 UTC by Seaman51

HW Lesson 2

2021-01-25 15:06 UTC, Vokler requested changes

2021-01-25 15:06 UTC, Vokler commented on mainapp/templates/mainapp/products.html
> +                                         src="{% static '' %}{{product.src}}"
Необязательно так делать, можно просто `{% static product.src %}`

2021-01-25 18:38 UTC, Seaman51 commented on mainapp/templates/mainapp/products.html
> +                                         src="{% static '' %}{{product.src}}"
Спасибо. Изменил.

2021-01-26 19:49 UTC, Vokler approved these changes

2021-01-26 19:49 UTC, merged